# Generated by Django 4.0.4 on 2022-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='cuerpo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='post',
            name='tipo_post',
            field=models.CharField(choices=[('Pelicula', 'Pelicula'), ('Libro', 'Libro')], default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogApp.tag'),
        ),
    ]
