# Generated by Django 4.0.4 on 2022-06-16 14:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='asd',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=23, upload_to='profile_pics', verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
