# Generated by Django 4.0.4 on 2022-06-16 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogApp', '0005_customuser_asd_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creado_en', to='blogApp.post')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.CharField(max_length=400),
        ),
    ]
