# Generated by Django 4.0.4 on 2022-06-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_alter_post_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_title', models.CharField(max_length=4000)),
                ('panel_price', models.CharField(max_length=200)),
                ('panel_link', models.CharField(max_length=4000)),
            ],
        ),
    ]
