# Generated by Django 4.0.4 on 2022-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_panels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panels',
            name='panel_price',
            field=models.FloatField(max_length=200),
        ),
    ]
